name: Build Windows EXE (PyInstaller + Inno Setup)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole main.py
          echo "PyInstaller finished. dist\\main.exe should exist."

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create Output dir
        run: mkdir Output || exit 0

      - name: Create installer (Inno Setup)
        shell: cmd
        run: |
          iscc setup.iss
          powershell -Command "New-Item -ItemType Directory -Force -Path Output; Get-ChildItem -Path . -Filter 'PassportPhotoExtractorSetup*.exe' -Recurse | ForEach-Object { Copy-Item $_ -Destination Output -Force }"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: PassportPhotoExtractorInstaller
          path: Output/*.exe

